pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Manual Approval') {
            steps {
                input message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed', submitter: 'user', parameters: [choice(name: 'ACTION', choices: ['Proceed', 'Abort'], description: 'Pilih tindakan')]
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                script {
                    echo "Waiting for 1 minute..."
                    sleep(time: 1, unit: 'MINUTES')
                    sh './jenkins/scripts/kill.sh'
                }
            }
        }
    }
}
